language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - cmake
      - libhwloc-dev
      - libopenmpi-dev
      - openmpi-bin
      - gcc-4.9
      - g++-4.9
before_install:
 - mkdir -p "$HOME/bin"
 - if [[ ${CMAKE_VERSION} ]]; then wget --no-check-certificate -qO- http://www.cmake.org/files/v${CMAKE_VERSION:0:3}/cmake-${CMAKE_VERSION}.tar.gz | tar -xz && ln -s $PWD/cmake-${CMAKE_VERSION}/bin/cmake "$HOME/bin/cmake"; fi
 - if [[ ${COVERAGE}  ]]; then pip install --user codecov; fi

env: #maybe add mpich later
  global:
    - CCACHE_CPP2=yes
    - CMAKE_VERSION=3.1.3-Linux-x86_64
    - GVER=4.9
  matrix:
    - COVERAGE=ON
    - USE_V4_SSE=ON
    - USE_V4_AVX=ON
    - USE_V4_PORTABLE=ON
    - USE_V4_AVX=ON USE_V8_AVX=ON
    - USE_V4_AVX=ON USE_V8_PORTABLE=ON

script:
  - mkdir build && cd build &&
    PATH="$HOME/bin:/usr/lib/ccache:$PATH" CC=gcc-${GVER} CXX=g++-${GVER} cmake -DENABLE_INTEGRATED_TESTS=ON -DENABLE_UNIT_TESTS=ON ${USE_V4_SSE:+-DUSE_V4_SSE=ON} ${USE_V4_PORTABLE:+-DUSE_V4_PORTABLE=ON} ${COVERAGE:+-DENABLE_COVERAGE_BUILD=ON} .. &&
    make -j4 VERBOSE=1 && make test CTEST_OUTPUT_ON_FAILURE=1 && make install DESTDIR=$PWD

after_success:
  - if [[ ${COVERAGE} ]]; then cd .. && codecov --gcov-exec gcov-${GVER}; fi

cache:
  directories:
    - $HOME/.ccache

compiler:
  - gcc
